name: ricks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # the job to build the ricks application
  build:
    name: Build
    
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: '16.17.0'
       
        run: npm install
      
      - name: Build the application
        run: npm run build --prod
